import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/NavBar";

// SpoqaHanSansNeo 폰트
// Regular 폰트
const spoqaHanSansNeoRegular = localFont({
  src: "./fonts/SpoqaHanSansNeo-Regular.woff2",
  weight: "400",
  variable: "--font-spoqa-han-sans-neo-regular",
});

// Bold 폰트
const spoqaHanSansNeoBold = localFont({
  src: "./fonts/SpoqaHanSansNeo-Bold.woff2",
  weight: "700",
  variable: "--font-spoqa-han-sans-neo-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${spoqaHanSansNeoRegular.variable} ${spoqaHanSansNeoBold.variable} antialiased`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
